stop



name: test-bot

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/12 * * * *'

jobs:
  test-bot:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    steps:
      - uses: actions/checkout@v2
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.1'
        
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
            
      - name: Run bot
      stop
        run: Rscript R/bot_script.R
        
